import { mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * Seed the intervention library with the ZOE Sleep Circadian interventions
 * Run this once to populate the library
 */
export const seedAll = mutation({
  args: {},
  returns: v.object({
    categories: v.number(),
    interventions: v.number(),
    bundles: v.number(),
  }),
  handler: async (ctx) => {
    const now = Date.now();
    let categoriesCreated = 0;
    let interventionsCreated = 0;
    let bundlesCreated = 0;

    // ============================================
    // CATEGORIES
    // ============================================
    const categories = [
      { category_id: "sleep_timing", name: "Sleep Timing & Regularity", description: "Interventions to stabilize sleep schedule", icon: "Clock", color: "#6366F1", order_index: 1 },
      { category_id: "light_dark", name: "Light & Dark", description: "Light exposure and darkness optimization", icon: "Sun", color: "#F59E0B", order_index: 2 },
      { category_id: "chrononutrition", name: "Chrononutrition", description: "Meal timing and eating windows", icon: "Utensils", color: "#10B981", order_index: 3 },
      { category_id: "supplements", name: "Supplements", description: "Sleep and relaxation supplements", icon: "Pill", color: "#8B5CF6", order_index: 4 },
      { category_id: "caffeine", name: "Caffeine & Stimulants", description: "Caffeine management strategies", icon: "Coffee", color: "#78350F", order_index: 5 },
      { category_id: "temperature", name: "Temperature & Thermal", description: "Temperature optimization for sleep", icon: "Thermometer", color: "#3B82F6", order_index: 6 },
      { category_id: "exercise", name: "Exercise", description: "Physical activity timing and dosing", icon: "Activity", color: "#EF4444", order_index: 7 },
      { category_id: "cbti", name: "CBT-I & Arousal Control", description: "Cognitive behavioral therapy for insomnia", icon: "Brain", color: "#EC4899", order_index: 8 },
      { category_id: "autonomic", name: "Autonomic & Ritual", description: "Relaxation and wind-down routines", icon: "Heart", color: "#F97316", order_index: 9 },
      { category_id: "environment", name: "Environment", description: "Bedroom environment optimization", icon: "Home", color: "#14B8A6", order_index: 10 },
      { category_id: "medical", name: "Medical Paths", description: "Medical screening and treatment paths", icon: "Stethoscope", color: "#DC2626", order_index: 11 },
      { category_id: "chronotherapy", name: "Chronotherapy", description: "Circadian phase shifting interventions", icon: "Moon", color: "#7C3AED", order_index: 12 },
    ];

    for (const cat of categories) {
      const existing = await ctx.db.query("intervention_categories").withIndex("by_category_id", q => q.eq("category_id", cat.category_id)).first();
      if (!existing) {
        await ctx.db.insert("intervention_categories", cat);
        categoriesCreated++;
      }
    }

    // ============================================
    // INTERVENTIONS
    // ============================================
    const interventions = [
      // Sleep Timing & Regularity
      {
        intervention_id: "WAKE-ANCHOR-01",
        name: "Fixed Wake-Time Anchor",
        short_name: "Wake Anchor",
        category: "sleep_timing",
        type: "behavioral",
        why_it_works: "Consistent wake time stabilizes SCN entrainment by anchoring morning light exposure, cortisol rhythm, and downstream feeding/activity timing.",
        how_to_apply: "Set wake time feasible 7 days/week; allow ±15–30 min variability. Do not force bedtime initially; let sleep pressure drive earlier onset as the system stabilizes. For severe sleep debt: short-term earlier bedtime allowed, but keep wake time fixed.",
        instructions_text: "Wake up at the same time every day, within 15-30 minutes. This includes weekends. Don't hit snooze - get out of bed at your set time.",
        target_phenotypes: ["DSPD", "late_chronotype", "irregular_rhythm"],
        target_gateways: ["insomnia", "circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Stabilizes circadian rhythm",
        bundle_ids: ["phase_advance_regularity", "rhythm_stabilization", "metabolic_circadian"],
      },
      {
        intervention_id: "SRI-01",
        name: "Sleep Regularity Target",
        short_name: "Sleep Regularity",
        category: "sleep_timing",
        type: "behavioral",
        why_it_works: "Irregular sleep timing is associated with cardiometabolic risk independent of duration; regularity supports circadian amplitude and sleep efficiency.",
        how_to_apply: "Track SD of sleep onset/offset from diaries/wearables. Goal 1: SD < 60 min; Goal 2: SD < 45 min; optimal < 30 min. Use morning routine + evening wind-down + weekend cap to improve.",
        instructions_text: "Keep your bedtime and wake time consistent. Aim for less than 45 minutes variation day-to-day. Track your sleep times to monitor progress.",
        target_phenotypes: ["irregular_rhythm"],
        target_gateways: ["insomnia", "metabolic_risk"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Reduces cardiometabolic risk",
        bundle_ids: ["rhythm_stabilization"],
      },
      {
        intervention_id: "SJL-01",
        name: "Social Jet Lag Reduction",
        short_name: "Weekend Stability",
        category: "sleep_timing",
        type: "behavioral",
        why_it_works: "Weekend phase shifts mimic jet lag and promote circadian misalignment and metabolic disruption.",
        how_to_apply: "Limit weekend sleep midpoint shift to ≤1 hour. If late night occurs: add morning outdoor light + early breakfast + earlier exercise next day.",
        instructions_text: "Don't sleep in more than 1 hour later on weekends. If you stay up late, still get morning light and eat breakfast early the next day.",
        target_phenotypes: ["irregular_rhythm", "late_chronotype"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "weekly",
        is_optional_addon: true,
        primary_benefit: "Prevents weekend circadian disruption",
      },
      {
        intervention_id: "CBTI-SR-01",
        name: "Sleep Restriction / Compression",
        short_name: "Sleep Restriction",
        category: "sleep_timing",
        type: "behavioral",
        why_it_works: "Consolidates sleep by increasing homeostatic drive; improves sleep efficiency and reduces time awake in bed.",
        how_to_apply: "Set time-in-bed = average sleep time (min 5h initially). Expand by 15–30 min once sleep efficiency >85–90% for 1 week. Contraindication: bipolar mania risk, seizure instability (use caution).",
        instructions_text: "Limit your time in bed to match your actual sleep time. Start with a minimum of 5 hours. Increase by 15-30 minutes when sleep efficiency improves.",
        target_phenotypes: ["insomnia_maintenance"],
        target_gateways: ["insomnia"],
        contraindications: ["bipolar disorder", "seizure disorder"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Consolidates fragmented sleep",
        bundle_ids: ["cbti_onset", "cbti_maintenance"],
      },

      // Light & Dark
      {
        intervention_id: "LIGHT-AM-01",
        name: "Morning Outdoor Light",
        short_name: "Morning Light",
        category: "light_dark",
        type: "behavioral",
        why_it_works: "Morning light advances/stabilizes the circadian phase and increases daytime alertness by entraining SCN pathways.",
        how_to_apply: "20–30 min outdoors within 1–2h of waking; 40–60 min for DSPD or cloudy days. Prefer outdoor over indoor light; no sunglasses unless necessary.",
        instructions_text: "Get 20-30 minutes of outdoor light within 1-2 hours of waking. Don't wear sunglasses. On cloudy days or if you have DSPD, aim for 40-60 minutes.",
        target_phenotypes: ["DSPD", "late_chronotype", "irregular_rhythm"],
        target_gateways: ["circadian_misalignment", "depression"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Advances circadian phase",
        bundle_ids: ["phase_advance_regularity", "rhythm_stabilization", "metabolic_circadian", "energy_stability"],
      },
      {
        intervention_id: "LIGHT-BOX-01",
        name: "Bright Light Therapy Box",
        short_name: "Light Box",
        category: "light_dark",
        type: "environmental",
        why_it_works: "High-lux light provides a controllable zeitgeber to shift circadian phase when outdoor light isn't enough.",
        how_to_apply: "Phase advance (delayed): use after waking, progressively earlier across days. Phase delay (advanced): use early evening; avoid late use in insomnia-prone patients. Start with 10–20 min and titrate to 30–45 min based on tolerance.",
        instructions_text: "Use a 10,000 lux light box for 20-45 minutes. For phase advance, use it right after waking. Start with shorter sessions and increase gradually.",
        target_phenotypes: ["DSPD", "ASPD", "seasonal_affective"],
        target_gateways: ["circadian_misalignment", "depression"],
        default_frequency: "daily",
        default_timing: "morning",
        is_optional_addon: true,
        primary_benefit: "Controlled phase shifting",
      },
      {
        intervention_id: "LIGHT-PM-01",
        name: "Evening Light Dimming",
        short_name: "Dim Evenings",
        category: "light_dark",
        type: "behavioral",
        why_it_works: "Reduces melatonin suppression and prevents phase delay from evening melanopsin activation.",
        how_to_apply: "2 hours before bedtime: <50 lux, warm lighting, avoid overhead bright LEDs. Pair with screen hygiene and/or blue-blockers for maximal effect.",
        instructions_text: "Dim lights 2 hours before bed. Use warm-colored bulbs. Keep light levels below 50 lux. Avoid bright overhead lights and screens.",
        target_phenotypes: ["DSPD", "late_chronotype"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Supports natural melatonin rise",
        bundle_ids: ["phase_advance_regularity", "cbti_onset"],
      },
      {
        intervention_id: "BBG-01",
        name: "Blue-Blocking Glasses",
        short_name: "Blue Blockers",
        category: "light_dark",
        type: "environmental",
        why_it_works: "Reduces short-wavelength light input to melanopsin, helping melatonin rise and sleep onset.",
        how_to_apply: "Wear last 2–3 hours before bed during screen use or bright indoor lighting. Use especially in teens, night owls, and high-screen occupations.",
        instructions_text: "Wear blue-blocking glasses for 2-3 hours before bed, especially when using screens or in bright indoor lighting.",
        target_phenotypes: ["DSPD", "late_chronotype"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "evening",
        is_optional_addon: true,
        primary_benefit: "Reduces evening blue light exposure",
        bundle_ids: ["phase_advance_regularity"],
      },
      {
        intervention_id: "DARK-01",
        name: "Darkness Optimization",
        short_name: "Dark Sleep",
        category: "light_dark",
        type: "environmental",
        why_it_works: "Eliminates light at night (LAN), supporting melatonin signal and improving sleep continuity.",
        how_to_apply: "Blackout curtains or eye mask; cover LEDs; avoid bright nightlights. If night bathroom trips: use dim red/amber guide lights.",
        instructions_text: "Make your bedroom completely dark. Use blackout curtains or an eye mask. Cover LED lights. Use dim red/amber lights if you need to get up at night.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia", "sleep_maintenance"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_core_intervention: true,
        primary_benefit: "Eliminates sleep-disrupting light",
        bundle_ids: ["phase_advance_regularity", "rhythm_stabilization", "osa_path"],
      },

      // Chrononutrition
      {
        intervention_id: "MEAL-ETRE-01",
        name: "Early Time-Restricted Eating",
        short_name: "Early Eating Window",
        category: "chrononutrition",
        type: "behavioral",
        why_it_works: "Aligns feeding with metabolic rhythms; supports peripheral clock alignment and improves glucose/BP outcomes.",
        how_to_apply: "Eating window 8–10 hours, preferably 07:00–15:00 or 08:00–18:00. Avoid late windows (e.g., 12:00–22:00) unless shift-work requires it.",
        instructions_text: "Eat all meals within an 8-10 hour window, ideally ending by 6 PM. Avoid eating late at night. Example: 8 AM to 6 PM.",
        target_phenotypes: ["metabolic_risk", "late_chronotype"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Aligns eating with metabolic rhythms",
        bundle_ids: ["phase_advance_regularity", "metabolic_circadian"],
      },
      {
        intervention_id: "MEAL-FIRST-01",
        name: "First Meal Timing",
        short_name: "Early Breakfast",
        category: "chrononutrition",
        type: "behavioral",
        why_it_works: "Early feeding anchors peripheral clocks and reduces late-day overeating; supports morning alertness.",
        how_to_apply: "First meal within 1–2h of waking; ideally before 09:00. For appetite-suppressed patients: protein shake or yogurt anchor.",
        instructions_text: "Eat your first meal within 1-2 hours of waking, ideally before 9 AM. Even a small protein-rich snack helps anchor your rhythms.",
        target_phenotypes: ["late_chronotype", "metabolic_risk"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Anchors peripheral clocks",
        bundle_ids: ["metabolic_circadian"],
      },
      {
        intervention_id: "MEAL-LAST-01",
        name: "Last Meal Timing",
        short_name: "Early Dinner",
        category: "chrononutrition",
        type: "behavioral",
        why_it_works: "Late eating worsens glycemic control and increases reflux and nocturnal arousal.",
        how_to_apply: "Last meaningful meal ≥3h before bedtime. If hungry: small snack (protein + fiber), not high sugar/fat.",
        instructions_text: "Finish your last meal at least 3 hours before bed. If hungry later, have only a small protein/fiber snack, not sugary or fatty foods.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia", "metabolic_risk", "gerd"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Reduces nocturnal disruption",
        bundle_ids: ["metabolic_circadian", "osa_path"],
      },
      {
        intervention_id: "MEAL-REG-01",
        name: "Meal Timing Regularity",
        short_name: "Regular Meals",
        category: "chrononutrition",
        type: "behavioral",
        why_it_works: "Irregular eating times create 'peripheral jet lag' in liver/pancreas clocks.",
        how_to_apply: "Keep meal times within ±1 hour day-to-day. Track eating window variability; aim to reduce week over week.",
        instructions_text: "Eat your meals at consistent times each day, within 1 hour of your usual times. This helps synchronize your body's internal clocks.",
        target_phenotypes: ["irregular_rhythm", "metabolic_risk"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Prevents peripheral clock desync",
        bundle_ids: ["rhythm_stabilization"],
      },
      {
        intervention_id: "WALK-POST-01",
        name: "Post-Meal Walk",
        short_name: "After-Dinner Walk",
        category: "chrononutrition",
        type: "behavioral",
        why_it_works: "Blunts postprandial glucose excursions and improves sleep stability by reducing nighttime glycemic swings.",
        how_to_apply: "10–20 min easy walk after dinner (or largest meal). Especially for insulin resistance/T2D/late eaters.",
        instructions_text: "Take a 10-20 minute easy walk after dinner. This helps stabilize blood sugar and improves sleep quality.",
        target_phenotypes: ["metabolic_risk"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Stabilizes glucose for better sleep",
        bundle_ids: ["metabolic_circadian"],
      },

      // Supplements
      {
        intervention_id: "SUP-GLY-01",
        name: "Glycine",
        short_name: "Glycine",
        category: "supplements",
        type: "supplement",
        why_it_works: "Improves subjective sleep quality and next-day fatigue; may support thermoregulation.",
        how_to_apply: "3 g, 30–60 min before bed (powder or capsules). Avoid if significant renal impairment; stop if GI upset.",
        instructions_text: "Take 3g of glycine 30-60 minutes before bed. Can be taken as powder mixed in water or as capsules.",
        contraindications: ["renal impairment"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        default_dosage: "3g",
        is_optional_addon: true,
        primary_benefit: "Improves sleep quality",
      },
      {
        intervention_id: "SUP-MAG-01",
        name: "Magnesium (glycinate)",
        short_name: "Magnesium",
        category: "supplements",
        type: "supplement",
        why_it_works: "Supports neuromuscular relaxation and parasympathetic tone in some patients (especially low intake).",
        how_to_apply: "200–400 mg elemental Mg in evening. Avoid in renal failure; monitor for diarrhea (switch form/dose).",
        instructions_text: "Take 200-400mg of magnesium glycinate in the evening. Start with lower dose and increase if tolerated.",
        contraindications: ["renal failure"],
        default_frequency: "daily",
        default_timing: "evening",
        default_dosage: "200-400mg",
        dosage_notes: "Elemental magnesium; glycinate form preferred for absorption and tolerability",
        is_optional_addon: true,
        primary_benefit: "Promotes relaxation",
      },
      {
        intervention_id: "SUP-THEA-01",
        name: "L-theanine",
        short_name: "L-theanine",
        category: "supplements",
        type: "supplement",
        why_it_works: "Promotes relaxation and reduces cognitive hyperarousal.",
        how_to_apply: "100–400 mg, ~60 min before bed; can be used situationally.",
        instructions_text: "Take 100-400mg of L-theanine about 60 minutes before bed. Can be used nightly or as needed for anxiety.",
        default_frequency: "daily",
        default_timing: "pre_bed",
        default_dosage: "200mg",
        is_optional_addon: true,
        primary_benefit: "Reduces mental hyperarousal",
      },
      {
        intervention_id: "SUP-CRE-01",
        name: "Creatine (daytime)",
        short_name: "Creatine",
        category: "supplements",
        type: "supplement",
        why_it_works: "Buffers brain energy metabolism, potentially improving cognition during short sleep periods.",
        how_to_apply: "3–5 g daily, morning/midday. Frame as resilience aid, not a sleep improver.",
        instructions_text: "Take 3-5g of creatine in the morning or midday. This supports cognitive function, especially during periods of sleep restriction.",
        default_frequency: "daily",
        default_timing: "morning",
        default_dosage: "5g",
        is_optional_addon: true,
        primary_benefit: "Supports cognition during sleep debt",
      },

      // Caffeine
      {
        intervention_id: "CAF-01",
        name: "Caffeine Curfew",
        short_name: "Caffeine Cutoff",
        category: "caffeine",
        type: "behavioral",
        why_it_works: "Prevents delayed sleep onset and reduced deep sleep due to caffeine half-life.",
        how_to_apply: "Last caffeine ≥8 hours before target bedtime. For insomnia/anxiety: morning-only caffeine.",
        instructions_text: "Stop all caffeine at least 8 hours before your target bedtime. If you have insomnia, limit caffeine to mornings only.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Prevents caffeine-related sleep disruption",
        bundle_ids: ["phase_advance_regularity", "energy_stability"],
      },
      {
        intervention_id: "CAF-CHRONO-01",
        name: "Chronotype-Specific Caffeine",
        short_name: "Smart Caffeine",
        category: "caffeine",
        type: "behavioral",
        why_it_works: "Prevents 'late caffeine → later sleep → more caffeine' feedback loop in owls.",
        how_to_apply: "Owls: small morning + optional early afternoon; strict curfew. Larks: single morning dose; avoid afternoon entirely.",
        instructions_text: "Night owls: small coffee in morning, optional small dose before 2 PM. Early birds: one morning dose only, no afternoon caffeine.",
        target_phenotypes: ["late_chronotype", "early_chronotype"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_optional_addon: true,
        primary_benefit: "Aligns caffeine with chronotype",
      },

      // Temperature
      {
        intervention_id: "TEMP-ROOM-01",
        name: "Cool Bedroom",
        short_name: "Cool Room",
        category: "temperature",
        type: "environmental",
        why_it_works: "Facilitates core temperature decline needed for sleep initiation/maintenance.",
        how_to_apply: "Target 16–19°C; adjust bedding rather than room temp when possible.",
        instructions_text: "Keep your bedroom between 16-19°C (60-67°F). Use appropriate bedding to stay comfortable rather than heating the room.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_core_intervention: true,
        primary_benefit: "Supports core temperature drop",
        bundle_ids: ["rhythm_stabilization", "osa_path"],
      },
      {
        intervention_id: "TEMP-BATH-01",
        name: "Warm Bath/Shower Pre-Bed",
        short_name: "Warm Bath",
        category: "temperature",
        type: "behavioral",
        why_it_works: "Promotes distal vasodilation and subsequent heat loss → faster sleep onset.",
        how_to_apply: "10–20 min warm bath/shower 1–2h before bed. Avoid in severe hypotension/unstable cardiac conditions.",
        instructions_text: "Take a warm bath or shower 1-2 hours before bed for 10-20 minutes. This helps trigger your body's natural cooling for sleep.",
        contraindications: ["severe hypotension", "unstable cardiac conditions"],
        default_frequency: "daily",
        default_timing: "evening",
        is_optional_addon: true,
        primary_benefit: "Triggers cooling for sleep onset",
        bundle_ids: ["cbti_onset"],
      },
      {
        intervention_id: "TEMP-SAUNA-01",
        name: "Sauna (early evening)",
        short_name: "Evening Sauna",
        category: "temperature",
        type: "behavioral",
        why_it_works: "Relaxation + post-sauna cooling may deepen sleep when not too close to bedtime.",
        how_to_apply: "Finish ≥3h before bedtime; hydrate; use caution in high CV risk.",
        instructions_text: "If using sauna, finish at least 3 hours before bed. Stay well hydrated. The post-sauna cooling can promote deeper sleep.",
        contraindications: ["high cardiovascular risk"],
        default_frequency: "weekly",
        default_timing: "evening",
        is_optional_addon: true,
        primary_benefit: "Deep relaxation and cooling",
      },
      {
        intervention_id: "TEMP-FEET-01",
        name: "Warm Feet Protocol",
        short_name: "Warm Feet",
        category: "temperature",
        type: "behavioral",
        why_it_works: "Distal warming helps heat dissipation and reduces sleep latency in cold-extremity phenotype.",
        how_to_apply: "Warm socks/hot water bottle during wind-down; avoid overheating core.",
        instructions_text: "If you have cold feet, wear warm socks or use a hot water bottle during wind-down. This helps your body release heat for sleep.",
        target_phenotypes: ["cold_extremities"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_optional_addon: true,
        primary_benefit: "Helps cold sleepers fall asleep",
      },

      // Exercise
      {
        intervention_id: "EX-DOSE-01",
        name: "Weekly Exercise Minimum",
        short_name: "Exercise Dose",
        category: "exercise",
        type: "behavioral",
        why_it_works: "Improves sleep quality, mood, insulin sensitivity, and circadian robustness.",
        how_to_apply: "150–300 min moderate OR 75–150 min vigorous + 2 resistance sessions/week.",
        instructions_text: "Get 150-300 minutes of moderate exercise OR 75-150 minutes of vigorous exercise per week, plus 2 strength training sessions.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia", "metabolic_risk", "depression"],
        default_frequency: "weekly",
        is_core_intervention: true,
        primary_benefit: "Foundation for sleep health",
        bundle_ids: ["metabolic_circadian", "energy_stability"],
      },
      {
        intervention_id: "EX-TIME-01",
        name: "Exercise Timing as Zeitgeber",
        short_name: "Timed Exercise",
        category: "exercise",
        type: "behavioral",
        why_it_works: "Exercise timing can shift circadian phase and improve rhythm amplitude.",
        how_to_apply: "For phase advance: late morning/early afternoon exercise. Avoid very vigorous exercise within 1–2h of bedtime in insomnia-prone patients.",
        instructions_text: "Exercise in late morning or early afternoon to help advance your sleep timing. Avoid intense exercise within 2 hours of bedtime.",
        target_phenotypes: ["DSPD", "late_chronotype"],
        target_gateways: ["circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Uses exercise to shift circadian phase",
        bundle_ids: ["phase_advance_regularity"],
      },

      // CBT-I & Arousal Control
      {
        intervention_id: "CBTI-SC-01",
        name: "Stimulus Control",
        short_name: "Stimulus Control",
        category: "cbti",
        type: "behavioral",
        why_it_works: "Deconditions bed–wakefulness association; improves sleep onset and maintenance.",
        how_to_apply: "Bed only for sleep/sex; no scrolling in bed. If awake >20–30 min, leave bed for dim, boring activity until sleepy.",
        instructions_text: "Use your bed only for sleep. If awake more than 20 minutes, get up and do something boring in dim light until sleepy. No phones in bed.",
        target_phenotypes: ["insomnia_onset", "insomnia_maintenance"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Reconditions bed-sleep association",
        bundle_ids: ["cbti_onset", "cbti_maintenance", "rhythm_stabilization"],
      },
      {
        intervention_id: "CBTI-COG-01",
        name: "Cognitive Restructuring",
        short_name: "Sleep Thoughts",
        category: "cbti",
        type: "behavioral",
        why_it_works: "Reduces catastrophic thoughts that fuel arousal and insomnia persistence.",
        how_to_apply: "Identify beliefs → challenge evidence → replace with realistic coping statements.",
        instructions_text: "Challenge negative sleep thoughts. Replace 'I'll never sleep' with realistic thoughts like 'I've gotten through this before and will again.'",
        target_phenotypes: ["insomnia_onset", "anxiety_predominant"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Reduces sleep anxiety",
        bundle_ids: ["cbti_onset"],
      },
      {
        intervention_id: "AROUSAL-01",
        name: "Worry Time / Cognitive Offload",
        short_name: "Worry Time",
        category: "cbti",
        type: "behavioral",
        why_it_works: "Moves rumination earlier; reduces bedtime cognitive activation.",
        how_to_apply: "15–20 min 'worry + next step' session 2–3h pre-bed; stop at cutoff.",
        instructions_text: "Schedule 15-20 minutes 2-3 hours before bed to write down worries and next steps. After this time, close the notebook and let it go.",
        target_phenotypes: ["anxiety_predominant", "racing_mind"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Moves worrying away from bedtime",
        bundle_ids: ["cbti_onset"],
      },

      // Autonomic & Ritual
      {
        intervention_id: "BREATH-01",
        name: "Slow Breathing",
        short_name: "Slow Breathing",
        category: "autonomic",
        type: "behavioral",
        why_it_works: "Increases parasympathetic tone and reduces sympathetic arousal.",
        how_to_apply: "5–10 min at 4–6 breaths/min during wind-down or awakenings.",
        instructions_text: "Practice slow breathing for 5-10 minutes: inhale 4-5 seconds, exhale 6-7 seconds. Use during wind-down or if you wake at night.",
        target_phenotypes: ["anxiety_predominant", "hyperarousal"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_core_intervention: true,
        primary_benefit: "Activates relaxation response",
        bundle_ids: ["cbti_onset"],
      },
      {
        intervention_id: "RITUAL-01",
        name: "Fixed Wind-Down Sequence",
        short_name: "Bedtime Routine",
        category: "autonomic",
        type: "behavioral",
        why_it_works: "Conditioning: repeatable cue chain trains sleepiness response.",
        how_to_apply: "Same 2–4 steps nightly; keep low-stimulation and dim light.",
        instructions_text: "Create a 20-30 minute bedtime routine with 2-4 consistent steps. Keep it calm and dim. Example: dim lights, brush teeth, read, breathing exercise.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_core_intervention: true,
        primary_benefit: "Conditions sleepiness cue",
        bundle_ids: ["rhythm_stabilization"],
      },
      {
        intervention_id: "SCREEN-01",
        name: "Screen Hygiene",
        short_name: "Screen Hygiene",
        category: "autonomic",
        type: "behavioral",
        why_it_works: "Reduces light exposure and mental stimulation that impair sleep onset.",
        how_to_apply: "Limit stimulating content 1-2h before bed; use night mode; prefer reading or relaxing content.",
        instructions_text: "Avoid stimulating screens 1-2 hours before bed. Use night mode. Choose relaxing content over news, social media, or exciting shows.",
        target_phenotypes: ["all"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Reduces pre-sleep stimulation",
        bundle_ids: ["cbti_onset"],
      },

      // Environment
      {
        intervention_id: "ENV-NOISE-01",
        name: "Noise Control",
        short_name: "Noise Control",
        category: "environment",
        type: "environmental",
        why_it_works: "Intermittent noise causes microarousals and sleep fragmentation.",
        how_to_apply: "Earplugs + white/brown noise; optimize room layout; consider soundproofing.",
        instructions_text: "Use earplugs and/or white noise machine. Block intermittent sounds that can disturb sleep. Consider soundproofing if needed.",
        target_phenotypes: ["noise_sensitive"],
        target_gateways: ["insomnia", "sleep_maintenance"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Prevents noise-induced awakenings",
        bundle_ids: ["rhythm_stabilization"],
      },
      {
        intervention_id: "ENV-HUMID-01",
        name: "Humidity 40-60%",
        short_name: "Humidity",
        category: "environment",
        type: "environmental",
        why_it_works: "Reduces nasal irritation/congestion and supports airway comfort.",
        how_to_apply: "Humidifier/dehumidifier; monitor mold risk if >60%.",
        instructions_text: "Maintain bedroom humidity between 40-60%. Use a humidifier in dry conditions or dehumidifier if too humid. Watch for mold at higher humidity.",
        target_phenotypes: ["nasal_congestion", "dry_climate"],
        target_gateways: ["sleep_apnea"],
        default_frequency: "daily",
        is_optional_addon: true,
        primary_benefit: "Supports nasal breathing",
      },
      {
        intervention_id: "ENV-WEIGHT-01",
        name: "Weighted Blanket",
        short_name: "Weighted Blanket",
        category: "environment",
        type: "environmental",
        why_it_works: "Deep pressure stimulation can reduce arousal in selected patients.",
        how_to_apply: "7–12% of body weight; avoid in respiratory compromise/frailty.",
        instructions_text: "Try a weighted blanket (7-12% of your body weight). Deep pressure can help reduce anxiety and promote relaxation.",
        contraindications: ["respiratory compromise", "frailty"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_optional_addon: true,
        primary_benefit: "Deep pressure calming",
      },

      // Medical Paths
      {
        intervention_id: "MED-OSA-01",
        name: "OSA/UARS Diagnostic Path",
        short_name: "Sleep Study",
        category: "medical",
        type: "medical",
        why_it_works: "Treating sleep-disordered breathing restores sleep architecture and daytime energy.",
        how_to_apply: "Screen systematically; HSAT/PSG; assess positionality, nasal obstruction, BMI, craniofacial factors.",
        instructions_text: "Get evaluated for sleep apnea with a home sleep test or in-lab study. This is important for treating snoring and breathing issues.",
        target_phenotypes: ["osa_risk"],
        target_gateways: ["sleep_apnea"],
        default_frequency: "once",
        is_core_intervention: true,
        primary_benefit: "Diagnoses treatable breathing disorders",
        bundle_ids: ["osa_path"],
      },
      {
        intervention_id: "NASAL-01",
        name: "Nasal Patency Optimization",
        short_name: "Nasal Care",
        category: "medical",
        type: "medical",
        why_it_works: "Reduced nasal resistance improves airflow and can reduce arousals/snoring in some patients.",
        how_to_apply: "Saline rinse; nasal steroids if indicated; nasal strips; evaluate structural obstruction.",
        instructions_text: "Optimize nasal breathing with saline rinses, nasal strips, or talk to your doctor about nasal sprays. Address any structural issues.",
        target_phenotypes: ["nasal_obstruction"],
        target_gateways: ["sleep_apnea"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_optional_addon: true,
        primary_benefit: "Improves nasal airflow",
        bundle_ids: ["osa_path"],
      },

      // Chronotherapy
      {
        intervention_id: "MEL-01",
        name: "Low-Dose Melatonin Phase Shift",
        short_name: "Melatonin",
        category: "chronotherapy",
        type: "supplement",
        why_it_works: "Melatonin is a circadian signal; timed low dose shifts phase more predictably than high sedative dosing.",
        how_to_apply: "≤1 mg immediate release. Phase advance: 5–6h before habitual bedtime; pair with strong morning light. Avoid 'sleep bomb' dosing unless specialist-directed.",
        instructions_text: "Take 0.5-1mg of melatonin 5-6 hours before your usual bedtime (not at bedtime). Combine with morning light exposure for best results.",
        target_phenotypes: ["DSPD", "late_chronotype"],
        target_gateways: ["circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "evening",
        default_dosage: "0.5-1mg",
        dosage_notes: "Low dose, immediate release; timing is critical - take 5-6h before habitual bedtime for phase advance",
        is_optional_addon: true,
        primary_benefit: "Phase-shifting circadian signal",
        bundle_ids: ["phase_advance_regularity"],
      },
      {
        intervention_id: "ROUTINE-AM-01",
        name: "Structured Morning Routine",
        short_name: "Morning Routine",
        category: "chronotherapy",
        type: "behavioral",
        why_it_works: "Consistent morning zeitgeber stack reinforces circadian entrainment.",
        how_to_apply: "Wake → light → movement → breakfast in consistent sequence each day.",
        instructions_text: "Create a consistent morning sequence: wake at set time, get bright light, do some movement, then eat breakfast. Same order daily.",
        target_phenotypes: ["irregular_rhythm", "DSPD"],
        target_gateways: ["circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Stacks morning zeitgebers",
        bundle_ids: ["rhythm_stabilization"],
      },
    ];

    for (const intv of interventions) {
      const existing = await ctx.db.query("interventions").withIndex("by_intervention_id", q => q.eq("intervention_id", intv.intervention_id)).first();
      if (!existing) {
        await ctx.db.insert("interventions", {
          intervention_id: intv.intervention_id,
          name: intv.name,
          short_name: intv.short_name,
          category: intv.category,
          type: intv.type,
          why_it_works: intv.why_it_works,
          how_to_apply: intv.how_to_apply,
          instructions_text: intv.instructions_text,
          target_phenotypes_json: intv.target_phenotypes ? JSON.stringify(intv.target_phenotypes) : undefined,
          target_gateways_json: intv.target_gateways ? JSON.stringify(intv.target_gateways) : undefined,
          contraindications_json: intv.contraindications ? JSON.stringify(intv.contraindications) : undefined,
          default_frequency: intv.default_frequency,
          default_timing: intv.default_timing,
          default_dosage: intv.default_dosage,
          dosage_notes: intv.dosage_notes,
          is_core_intervention: intv.is_core_intervention,
          is_optional_addon: intv.is_optional_addon,
          primary_benefit: intv.primary_benefit,
          bundle_ids_json: intv.bundle_ids ? JSON.stringify(intv.bundle_ids) : undefined,
          status: "active",
          version: 1,
          created_at: now,
          updated_at: now,
        });
        interventionsCreated++;
      }
    }

    // ============================================
    // BUNDLES
    // ============================================
    const bundles = [
      {
        bundle_id: "phase_advance_regularity",
        name: "Phase Advance + Regularity",
        description: "Bundle for late chronotypes (DSPD) focusing on advancing circadian phase and stabilizing rhythm amplitude.",
        goal: "Advance circadian phase and stabilize amplitude",
        target_phenotypes: ["DSPD", "late_chronotype"],
        target_gateways: ["circadian_misalignment", "insomnia"],
        core_intervention_ids: ["WAKE-ANCHOR-01", "LIGHT-AM-01", "LIGHT-PM-01", "DARK-01", "MEAL-ETRE-01", "EX-TIME-01", "CAF-01"],
        optional_intervention_ids: ["MEL-01", "BBG-01", "NAP-01"],
        recommended_count: 7,
        tracking_metrics: ["regularity", "light_timing", "sleepiness", "adherence"],
      },
      {
        bundle_id: "rhythm_stabilization",
        name: "Rhythm Stabilization",
        description: "Bundle for irregular sleep schedules to reduce variability and increase rhythmic robustness.",
        goal: "Reduce variability, increase rhythmic robustness",
        target_phenotypes: ["irregular_rhythm", "shift_work"],
        target_gateways: ["circadian_misalignment", "metabolic_risk"],
        core_intervention_ids: ["WAKE-ANCHOR-01", "SRI-01", "MEAL-REG-01", "LIGHT-AM-01", "ROUTINE-AM-01", "ENV-NOISE-01", "TEMP-ROOM-01"],
        optional_intervention_ids: ["CBTI-SC-01"],
        recommended_count: 7,
        tracking_metrics: ["sleep_regularity_index", "variability"],
      },
      {
        bundle_id: "cbti_onset",
        name: "CBT-I Onset + Hyperarousal",
        description: "Cognitive-behavioral bundle for sleep onset insomnia with evening dark and autonomic downshift.",
        goal: "Reduce hyperarousal and recondition sleep cues",
        target_phenotypes: ["insomnia_onset", "anxiety_predominant", "racing_mind"],
        target_gateways: ["insomnia", "anxiety"],
        core_intervention_ids: ["CBTI-SC-01", "CBTI-COG-01", "AROUSAL-01", "BREATH-01", "LIGHT-PM-01", "SCREEN-01", "TEMP-BATH-01"],
        optional_intervention_ids: ["SUP-THEA-01", "SUP-MAG-01"],
        recommended_count: 7,
        tracking_metrics: ["sleep_latency", "anxiety_level", "pre_sleep_arousal"],
      },
      {
        bundle_id: "cbti_maintenance",
        name: "CBT-I Maintenance",
        description: "Bundle for maintenance insomnia focusing on environment and sleep consolidation.",
        goal: "Consolidate fragmented sleep",
        target_phenotypes: ["insomnia_maintenance"],
        target_gateways: ["insomnia", "sleep_maintenance"],
        core_intervention_ids: ["CBTI-SR-01", "CBTI-SC-01", "DARK-01", "TEMP-ROOM-01", "ENV-NOISE-01"],
        optional_intervention_ids: ["MED-OSA-01"],
        recommended_count: 5,
        tracking_metrics: ["waso", "sleep_efficiency", "awakenings"],
      },
      {
        bundle_id: "metabolic_circadian",
        name: "Metabolic-Circadian Bundle",
        description: "Bundle for metabolic concerns (insulin resistance, obesity, nondipping BP) aligning peripheral clocks.",
        goal: "Align peripheral clocks via food timing + light + activity",
        target_phenotypes: ["metabolic_risk", "obesity", "insulin_resistance"],
        target_gateways: ["metabolic_risk"],
        core_intervention_ids: ["MEAL-ETRE-01", "MEAL-FIRST-01", "MEAL-LAST-01", "WALK-POST-01", "LIGHT-AM-01", "EX-DOSE-01", "WAKE-ANCHOR-01"],
        optional_intervention_ids: ["MEAL-REG-01"],
        recommended_count: 7,
        tracking_metrics: ["eating_window", "meal_timing", "glucose", "weight"],
      },
      {
        bundle_id: "osa_path",
        name: "OSA/UARS Path",
        description: "Bundle for sleep-disordered breathing focusing on airway and circadian support.",
        goal: "Treat breathing disruption + stabilize circadian behaviors",
        target_phenotypes: ["osa_risk", "snoring"],
        target_gateways: ["sleep_apnea"],
        core_intervention_ids: ["MED-OSA-01", "DARK-01", "TEMP-ROOM-01", "MEAL-LAST-01", "NASAL-01"],
        optional_intervention_ids: ["ENV-HUMID-01"],
        recommended_count: 5,
        tracking_metrics: ["ahi", "snoring", "oxygen_sat"],
      },
      {
        bundle_id: "energy_stability",
        name: "Energy-Stability Bundle",
        description: "Bundle for daytime fatigue without metabolic risk, focusing on sleep pressure and alertness.",
        goal: "Improve daytime energy via sleep quality optimization",
        target_phenotypes: ["daytime_fatigue"],
        target_gateways: ["excessive_sleepiness"],
        core_intervention_ids: ["LIGHT-AM-01", "CAF-01", "EX-DOSE-01", "WAKE-ANCHOR-01"],
        optional_intervention_ids: ["SUP-CRE-01"],
        recommended_count: 4,
        tracking_metrics: ["energy_level", "sleepiness", "alertness"],
      },
    ];

    for (const bundle of bundles) {
      const existing = await ctx.db.query("intervention_bundles").withIndex("by_bundle_id", q => q.eq("bundle_id", bundle.bundle_id)).first();
      if (!existing) {
        await ctx.db.insert("intervention_bundles", {
          bundle_id: bundle.bundle_id,
          name: bundle.name,
          description: bundle.description,
          goal: bundle.goal,
          target_phenotypes_json: JSON.stringify(bundle.target_phenotypes),
          target_gateways_json: bundle.target_gateways ? JSON.stringify(bundle.target_gateways) : undefined,
          core_intervention_ids_json: JSON.stringify(bundle.core_intervention_ids),
          optional_intervention_ids_json: bundle.optional_intervention_ids ? JSON.stringify(bundle.optional_intervention_ids) : undefined,
          recommended_count: bundle.recommended_count,
          tracking_metrics_json: bundle.tracking_metrics ? JSON.stringify(bundle.tracking_metrics) : undefined,
          status: "active",
          created_at: now,
          updated_at: now,
        });
        bundlesCreated++;
      }
    }

    return {
      categories: categoriesCreated,
      interventions: interventionsCreated,
      bundles: bundlesCreated,
    };
  },
});
