import { mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * Seed the intervention library with the ZOE Sleep Scientific Interventions v2
 * Based on AHA circadian health framework and clinical guidelines
 * Run this once to populate the library
 */
export const seedAll = mutation({
  args: {},
  returns: v.object({
    categories: v.number(),
    interventions: v.number(),
    bundles: v.number(),
  }),
  handler: async (ctx) => {
    const now = Date.now();
    let categoriesCreated = 0;
    let interventionsCreated = 0;
    let bundlesCreated = 0;

    // ============================================
    // CATEGORIES (organized by AHA circadian framework)
    // ============================================
    const categories = [
      { category_id: "cbti", name: "CBT-I Core", description: "Behavioral & cognitive interventions for insomnia (AASM first-line)", icon: "Brain", color: "#EC4899", order_index: 1 },
      { category_id: "circadian_light", name: "Circadian & Light", description: "Light timing and phase management", icon: "Sun", color: "#F59E0B", order_index: 2 },
      { category_id: "sleep_schedule", name: "Sleep Schedule", description: "Sleep regularity and timing engineering", icon: "Clock", color: "#6366F1", order_index: 3 },
      { category_id: "chrononutrition", name: "Chrononutrition", description: "Meal timing and metabolic alignment", icon: "Utensils", color: "#10B981", order_index: 4 },
      { category_id: "caffeine", name: "Caffeine Tactics", description: "Caffeine timing and management", icon: "Coffee", color: "#78350F", order_index: 5 },
      { category_id: "thermoregulation", name: "Thermoregulation", description: "Temperature optimization for sleep", icon: "Thermometer", color: "#3B82F6", order_index: 6 },
      { category_id: "environment", name: "Environment", description: "Noise, darkness, and bedroom optimization", icon: "Home", color: "#14B8A6", order_index: 7 },
      { category_id: "supplements", name: "Supplements", description: "Evidence-based sleep supplements", icon: "Pill", color: "#8B5CF6", order_index: 8 },
      { category_id: "exercise", name: "Exercise Timing", description: "Physical activity timing and dosing", icon: "Activity", color: "#EF4444", order_index: 9 },
      { category_id: "perimenopause", name: "Perimenopause", description: "Sleep + thermoregulation for menopause", icon: "Heart", color: "#F97316", order_index: 10 },
      { category_id: "medical", name: "Medical Screens", description: "Required diagnostic screenings", icon: "Stethoscope", color: "#DC2626", order_index: 11 },
    ];

    for (const cat of categories) {
      const existing = await ctx.db.query("intervention_categories").withIndex("by_category_id", q => q.eq("category_id", cat.category_id)).first();
      if (!existing) {
        await ctx.db.insert("intervention_categories", cat);
        categoriesCreated++;
      }
    }

    // ============================================
    // INTERVENTIONS (from ZOE Scientific Library v2)
    // Evidence: A = RCTs/meta-analyses, B = some RCTs/observational, C = mechanism/limited data, D = expert consensus
    // ============================================
    const interventions = [
      // ========== CBT-I Core (Evidence A) ==========
      {
        intervention_id: "CBTI-SC-01",
        name: "Stimulus Control",
        short_name: "Stimulus Control",
        category: "cbti",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Re-associates bed with sleep; extinguishes conditioned arousal. First-line for chronic insomnia per AASM guideline.",
        how_to_apply: "Bed only for sleep/sex; if awake ~15-20 min, leave bed to quiet activity in dim light, return when sleepy. Break the bed-wakefulness association.",
        instructions_text: "Use your bed only for sleep. If you're awake for more than 15-20 minutes, get up and do something calm in dim light until you feel sleepy, then return to bed.",
        target_phenotypes: ["SOL", "WASO", "anxiety_in_bed"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_core_intervention: true,
        primary_benefit: "Reconditions bed-sleep association",
        bundle_ids: ["delayed_phase_insomnia", "maintenance_insomnia"],
      },
      {
        intervention_id: "CBTI-SR-01",
        name: "Sleep Restriction / Compression",
        short_name: "Sleep Restriction",
        category: "cbti",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Increases homeostatic sleep drive; consolidates sleep; reduces WASO. Sets fixed wake time with time-in-bed matching average sleep time.",
        how_to_apply: "Set fixed wake time; time-in-bed ≈ average sleep time (minimum safety floor 5-6h). Titrate weekly by 15-30 min when sleep efficiency >85%.",
        instructions_text: "Set your wake time and stick to it daily. Initially limit time in bed to match your actual sleep time (minimum 5-6 hours). Expand by 15-30 minutes weekly as sleep improves.",
        target_phenotypes: ["WASO", "chronic_insomnia", "long_time_in_bed"],
        target_gateways: ["insomnia"],
        contraindications: ["bipolar disorder", "seizure disorder", "severe_sleep_deprivation"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Consolidates fragmented sleep",
        bundle_ids: ["delayed_phase_insomnia", "maintenance_insomnia"],
      },
      {
        intervention_id: "CBTI-COG-01",
        name: "Cognitive Therapy for Insomnia",
        short_name: "Sleep Thoughts",
        category: "cbti",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Reduces catastrophic beliefs ('If I don't sleep, I'll die tomorrow'), reduces hyperarousal. Challenges insomnia-perpetuating fears.",
        how_to_apply: "Structured thought records; 'probability vs possibility' reframes; behavioral experiments. Address rumination and performance anxiety.",
        instructions_text: "When anxious thoughts about sleep arise, write them down and challenge them. Ask: 'What's the evidence? Have I survived poor sleep before?' Replace catastrophic thoughts with realistic ones.",
        target_phenotypes: ["rumination", "performance_anxiety", "fear_of_sleeplessness"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Reduces sleep anxiety",
        bundle_ids: ["delayed_phase_insomnia"],
      },
      {
        intervention_id: "CBTI-RELAX-01",
        name: "Relaxation Training",
        short_name: "Relaxation",
        category: "cbti",
        type: "behavioral",
        evidence_score: 4, // A-B
        why_it_works: "Downshifts sympathetic tone; reduces pre-sleep arousal through progressive muscle relaxation, slow breathing, or mindfulness.",
        how_to_apply: "10-20 min pre-bed practice. Options: progressive muscle relaxation (tense-release muscle groups), slow breathing (4-7-8 or box breathing), body scan mindfulness.",
        instructions_text: "Practice relaxation 10-20 minutes before bed. Try progressive muscle relaxation (tense and release each muscle group) or slow breathing (inhale 4 sec, hold 7 sec, exhale 8 sec).",
        target_phenotypes: ["SOL", "stress", "somatic_tension"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_core_intervention: true,
        primary_benefit: "Reduces pre-sleep arousal",
        bundle_ids: ["delayed_phase_insomnia"],
      },
      {
        intervention_id: "CBTI-PI-01",
        name: "Paradoxical Intention",
        short_name: "Paradoxical Intention",
        category: "cbti",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Removes performance pressure, reduces 'trying to sleep' which paradoxically makes sleep harder. Breaks the effort-anxiety loop.",
        how_to_apply: "In bed, 'try to stay awake calmly' (no screens/phones). Let eyes stay open naturally. The goal is to remove the pressure to fall asleep.",
        instructions_text: "Instead of trying to fall asleep, try to stay awake calmly with your eyes open (no screens). This reduces the pressure that keeps you awake.",
        target_phenotypes: ["SOL", "perfectionism", "high_effort_sleeper"],
        target_gateways: ["insomnia"],
        default_frequency: "as_needed",
        default_timing: "pre_bed",
        is_optional_addon: true,
        primary_benefit: "Reduces performance pressure",
      },

      // ========== Circadian & Light (Evidence A-B) ==========
      {
        intervention_id: "LIGHT-AM-01",
        name: "Morning Bright Light",
        short_name: "Morning Light",
        category: "circadian_light",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Advances circadian phase; boosts alertness via SCN and melanopsin pathways; anchors rhythm. Key zeitgeber for phase control.",
        how_to_apply: "10-30 min outdoors soon after waking; cloudy days still helpful; avoid sunglasses if safe. For delayed phase, aim for 20-30 min within 1 hour of waking.",
        instructions_text: "Get 10-30 minutes of outdoor light within 1 hour of waking. Even cloudy days help. Don't wear sunglasses during this time if it's safe.",
        target_phenotypes: ["delayed_phase", "groggy_mornings", "irregular_schedule", "winter_low_daylight"],
        target_gateways: ["circadian_misalignment", "depression"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Advances and stabilizes circadian phase",
        bundle_ids: ["delayed_phase_insomnia", "cardiometabolic_alignment"],
      },
      {
        intervention_id: "LIGHT-PM-01",
        name: "Evening Light Avoidance",
        short_name: "Dim Evenings",
        category: "circadian_light",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Reduces melatonin suppression and phase delay; supports sleep initiation. Overhead LEDs are particularly disruptive.",
        how_to_apply: "Dim lights 1-2 hours before bed; reduce overhead LEDs; use low, warm lamps. Keep lights below 50 lux in the hour before bed.",
        instructions_text: "Dim your lights 1-2 hours before bed. Turn off bright overhead lights and use warm, low lamps instead. This helps your body prepare for sleep.",
        target_phenotypes: ["SOL", "delayed_phase", "screen_heavy_nights"],
        target_gateways: ["insomnia", "circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Supports natural melatonin rise",
        bundle_ids: ["delayed_phase_insomnia", "fragile_sleeper"],
      },
      {
        intervention_id: "LIGHT-BLUE-01",
        name: "Blue Light Reduction",
        short_name: "Blue Blockers",
        category: "circadian_light",
        type: "environmental",
        evidence_score: 3, // B
        why_it_works: "Melanopsin is most sensitive to short wavelengths; reducing blue content lowers circadian activation when screen use is unavoidable.",
        how_to_apply: "Night-mode + dim + distance on screens; consider amber lenses for high sensitivity patients. Most effective in the 2-3 hours before bed.",
        instructions_text: "Enable night mode on all devices. Dim screens and hold them further away. Consider amber/orange glasses if you're very light-sensitive in evenings.",
        target_phenotypes: ["cannot_reduce_screen_use", "light_sensitive"],
        target_gateways: ["insomnia", "circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "evening",
        is_optional_addon: true,
        primary_benefit: "Reduces evening screen light impact",
        bundle_ids: ["delayed_phase_insomnia"],
      },
      {
        intervention_id: "LIGHT-BOX-01",
        name: "Light Therapy Box",
        short_name: "Light Box",
        category: "circadian_light",
        type: "environmental",
        evidence_score: 4, // A-B
        why_it_works: "Timed bright light is a strong phase-reset tool (zeitgeber). 10,000 lux light therapy can shift circadian phase when outdoor light isn't feasible.",
        how_to_apply: "Clinician-timed dosing; morning for delays (20-45 min after waking); evening for advances (rare). Start with 15-20 min and titrate.",
        instructions_text: "Use a 10,000 lux light box for 20-30 minutes after waking. Position it at eye level, about 16-24 inches away. Don't stare directly at it.",
        target_phenotypes: ["DSPS", "shift_work", "seasonal_depression", "limited_outdoor_access"],
        target_gateways: ["circadian_misalignment", "depression"],
        default_frequency: "daily",
        default_timing: "morning",
        is_optional_addon: true,
        primary_benefit: "Controlled circadian phase shifting",
        bundle_ids: ["delayed_phase_insomnia"],
      },
      {
        intervention_id: "DARK-01",
        name: "Dark Therapy / Strict Darkness",
        short_name: "Dark Window",
        category: "circadian_light",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Strengthens amplitude of circadian rhythms; may reduce insomnia variability. Consistent 'dark window' supports melatonin production.",
        how_to_apply: "Consistent 'dark window' nightly (e.g., 10 PM - 6 AM); pair with morning light. Use blackout curtains, cover LEDs, avoid any bright light exposure.",
        instructions_text: "Create a consistent 'dark window' each night (e.g., 10 PM to 6 AM) where you avoid all bright light. Use blackout curtains and cover any LEDs in your bedroom.",
        target_phenotypes: ["irregular_rhythm", "shift_work"],
        target_gateways: ["circadian_misalignment", "insomnia"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Strengthens circadian amplitude",
        bundle_ids: ["fragile_sleeper"],
      },

      // ========== Sleep Schedule (Evidence A) ==========
      {
        intervention_id: "WAKE-ANCHOR-01",
        name: "Fixed Wake Time Anchor",
        short_name: "Wake Anchor",
        category: "sleep_schedule",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Stabilizes circadian phase; builds sleep pressure predictably. Wake time is the most powerful schedule lever - more important than bedtime.",
        how_to_apply: "Wake time within ±30 min daily; weekends included. Don't vary more than 30 minutes even if you slept poorly. Let bedtime float based on sleepiness.",
        instructions_text: "Wake up at the same time every day, within 30 minutes - including weekends. This is the single most important thing you can do for sleep regularity.",
        target_phenotypes: ["irregular_schedule", "all_phenotypes"],
        target_gateways: ["insomnia", "circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Anchors circadian rhythm",
        bundle_ids: ["delayed_phase_insomnia", "cardiometabolic_alignment", "fragile_sleeper"],
      },
      {
        intervention_id: "SJL-01",
        name: "Social Jet Lag Minimization",
        short_name: "Weekend Stability",
        category: "sleep_schedule",
        type: "behavioral",
        evidence_score: 4, // A-B
        why_it_works: "Weekend shifts mimic mini jet-lag; destabilize clocks. Irregular sleep timing associates with cardiovascular events and mortality risk.",
        how_to_apply: "Limit weekend wake delay to ~1 hour; use short naps instead of huge sleep-ins. If you stay up late, still wake close to your usual time.",
        instructions_text: "Don't sleep in more than 1 hour on weekends. If you're tired from a late night, take a short nap instead of sleeping until noon.",
        target_phenotypes: ["monday_insomnia", "late_weekend_sleepins"],
        target_gateways: ["circadian_misalignment"],
        default_frequency: "weekly",
        is_core_intervention: true,
        primary_benefit: "Prevents weekend circadian disruption",
        bundle_ids: ["delayed_phase_insomnia"],
      },

      // ========== Chrononutrition (Evidence A-B) ==========
      {
        intervention_id: "ETRE-01",
        name: "Early Time-Restricted Eating",
        short_name: "Early TRE",
        category: "chrononutrition",
        type: "behavioral",
        evidence_score: 4, // A-B
        why_it_works: "Aligns food with circadian insulin sensitivity; supports glucose control and BP. Improves insulin sensitivity in prediabetes (Sutton et al. Cell Metab 2018).",
        how_to_apply: "6-10 hour feeding window earlier in the day; finish dinner before mid/late afternoon in strict versions; adapt realistically to lifestyle.",
        instructions_text: "Eat all your meals within a 6-10 hour window, starting earlier in the day. Example: eat between 8 AM and 6 PM. Avoid eating late at night.",
        target_phenotypes: ["cardiometabolic_risk", "late_night_eating", "reflux"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Aligns eating with metabolic rhythms",
        bundle_ids: ["cardiometabolic_alignment"],
      },
      {
        intervention_id: "MEAL-LAST-01",
        name: "No Big Meal Late",
        short_name: "Early Dinner",
        category: "chrononutrition",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Late intake impairs glucose tolerance; increases reflux and thermal load. Eating late raises core temperature which interferes with sleep.",
        how_to_apply: "Finish last substantial meal 2-4 hours before bed; small protein snack only if needed for hunger. Avoid high-fat, high-sugar late meals.",
        instructions_text: "Finish your last big meal 2-4 hours before bed. If you're hungry later, have only a small protein snack - not a full meal or sugary foods.",
        target_phenotypes: ["SOL", "WASO", "GERD", "glucose_variability"],
        target_gateways: ["insomnia", "metabolic_risk"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Reduces nocturnal disruption",
        bundle_ids: ["delayed_phase_insomnia", "cardiometabolic_alignment"],
      },
      {
        intervention_id: "ALCOHOL-01",
        name: "Alcohol Timing Avoidance",
        short_name: "Alcohol Cutoff",
        category: "chrononutrition",
        type: "behavioral",
        evidence_score: 4, // A-B
        why_it_works: "Alcohol fragments sleep, suppresses REM early then rebounds; worsens SDB risk. Even moderate alcohol close to bed disrupts sleep architecture.",
        how_to_apply: "Set 'last alcohol' ≥3-4 hours pre-bed; counsel harm-reduction not moralizing. Earlier is better for sleep quality.",
        instructions_text: "Stop drinking alcohol at least 3-4 hours before bed. Even though alcohol feels sedating, it actually fragments your sleep later in the night.",
        target_phenotypes: ["WASO", "nonrestorative_sleep", "OSA_risk"],
        target_gateways: ["insomnia", "sleep_apnea"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Prevents alcohol-induced fragmentation",
      },

      // ========== Caffeine (Evidence A) ==========
      {
        intervention_id: "CAFF-CUTOFF-01",
        name: "Caffeine Cutoff",
        short_name: "Caffeine Cutoff",
        category: "caffeine",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Caffeine blocks adenosine; delays sleep and reduces total sleep time. 400mg caffeine even 6 hours before bed significantly disrupts sleep (Drake et al. 2013).",
        how_to_apply: "Avoid substantial caffeine within ≥6 hours of bedtime; for sensitive patients, 8-10 hours. Half-life varies by individual.",
        instructions_text: "Stop all caffeine at least 6 hours before bed. If you're caffeine-sensitive, make it 8-10 hours. Remember that tea and chocolate contain caffeine too.",
        target_phenotypes: ["SOL", "WASO", "shallow_sleep", "anxiety"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Prevents caffeine sleep disruption",
        bundle_ids: ["delayed_phase_insomnia", "cardiometabolic_alignment"],
      },
      {
        intervention_id: "CAFF-GATE-01",
        name: "Caffeine Gate (Delayed First Dose)",
        short_name: "Morning Caffeine Gate",
        category: "caffeine",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Prevents tolerance escalation and afternoon crash cycling. Delaying first caffeine allows natural cortisol awakening response.",
        how_to_apply: "Delay first caffeine 60-90 min after waking; cap daily dose; keep consistent timing. Let your body wake up naturally first.",
        instructions_text: "Wait 60-90 minutes after waking before your first coffee. This lets your body's natural wake-up system work first and prevents building tolerance.",
        target_phenotypes: ["fatigue", "heavy_caffeine_intake"],
        target_gateways: ["excessive_sleepiness"],
        default_frequency: "daily",
        default_timing: "morning",
        is_optional_addon: true,
        primary_benefit: "Optimizes caffeine effectiveness",
      },
      {
        intervention_id: "CAFF-NAP-01",
        name: "Strategic Nap + Caffeine",
        short_name: "Coffee Nap",
        category: "caffeine",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Short nap + caffeine onset can improve alertness without late-day intake. Caffeine takes 20 min to kick in, matching nap duration.",
        how_to_apply: "10-20 min nap; drink caffeine immediately before nap; avoid late afternoon. The caffeine kicks in as you wake, boosting alertness.",
        instructions_text: "For an afternoon energy boost: drink coffee, then immediately take a 10-20 minute nap. The caffeine kicks in as you wake. Only do this before 2 PM.",
        target_phenotypes: ["daytime_sleepiness", "shift_work"],
        target_gateways: ["excessive_sleepiness"],
        default_frequency: "as_needed",
        default_timing: "afternoon",
        is_optional_addon: true,
        primary_benefit: "Boosts alertness without late caffeine",
      },

      // ========== Thermoregulation (Evidence A-B) ==========
      {
        intervention_id: "BATH-01",
        name: "Warm Bath/Shower Pre-Bed",
        short_name: "Warm Bath",
        category: "thermoregulation",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Peripheral vasodilation → faster heat loss → core temp drop → sleep propensity. Meta-analysis supports 1-2h before bed (Haghayegh et al. 2019).",
        how_to_apply: "10-20 min warm (not scalding) bath or shower 1-2 hours before bed; then allow cool-down period. Water temp around 40-42°C (104-108°F).",
        instructions_text: "Take a warm (not hot) bath or shower 1-2 hours before bed for 10-20 minutes. This triggers your body's natural cooling, which promotes sleep.",
        target_phenotypes: ["SOL", "restless_evenings", "older_adults"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "evening",
        is_core_intervention: true,
        primary_benefit: "Triggers sleep-promoting cooling",
        bundle_ids: ["fragile_sleeper"],
      },
      {
        intervention_id: "FEET-01",
        name: "Warm Feet Protocol",
        short_name: "Warm Feet",
        category: "thermoregulation",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Distal vasodilation supports heat dissipation from the core. Warm feet help the body release heat, promoting sleep onset.",
        how_to_apply: "Warm feet 20-30 min before bed using foot bath, warm socks, or hot water bottle. Avoid overheating trunk/core.",
        instructions_text: "Warm your feet 20-30 minutes before bed with a foot bath, warm socks, or hot water bottle at your feet. Keep the rest of your body cool.",
        target_phenotypes: ["cold_feet", "SOL", "older_adults"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_optional_addon: true,
        primary_benefit: "Helps cold sleepers fall asleep",
      },
      {
        intervention_id: "COOL-ROOM-01",
        name: "Cool Bedroom",
        short_name: "Cool Room",
        category: "thermoregulation",
        type: "environmental",
        evidence_score: 3, // B
        why_it_works: "Supports nocturnal core temp decline and reduces awakenings. The body naturally cools during sleep; a cool room facilitates this.",
        how_to_apply: "Trial bedroom temp ~17-19°C (63-66°F); patient comfort rules; breathable bedding. Adjust based on individual preference.",
        instructions_text: "Keep your bedroom cool, around 17-19°C (63-66°F). Use breathable bedding and adjust to your comfort. A cool room helps your body's natural sleep cooling.",
        target_phenotypes: ["hot_sleeper", "perimenopause_hot_flashes"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Supports natural temperature drop",
        bundle_ids: ["fragile_sleeper"],
      },
      {
        intervention_id: "SAUNA-01",
        name: "Sauna (Early Evening)",
        short_name: "Evening Sauna",
        category: "thermoregulation",
        type: "behavioral",
        evidence_score: 2, // B-C
        why_it_works: "Strong thermal stimulus; may deepen subsequent cooling drive; improves relaxation. Must be timed correctly.",
        how_to_apply: "Keep ≥3-4 hours before bed; avoid dehydration; screen for cardiac risk. Rehydrate and allow full cool-down before bed.",
        instructions_text: "If using sauna, finish at least 3-4 hours before bed. Stay well hydrated. The post-sauna cooling can promote deeper sleep.",
        contraindications: ["significant_cardiac_risk", "hypotension"],
        target_phenotypes: ["stress", "athletes"],
        default_frequency: "weekly",
        default_timing: "evening",
        is_optional_addon: true,
        primary_benefit: "Deep relaxation and cooling",
      },
      {
        intervention_id: "COLD-AM-01",
        name: "Cold Exposure (Morning)",
        short_name: "Cold Shower",
        category: "thermoregulation",
        type: "behavioral",
        evidence_score: 1, // C
        why_it_works: "Alerting, sympathetic activation; may help morning energy and inflammation. Use for wake-up, NOT for sleep.",
        how_to_apply: "Morning exposure only; avoid right before bed if hyperarousal. Start with 30-60 seconds and gradually increase.",
        instructions_text: "A brief cold shower in the morning can boost alertness and energy. Do NOT use this before bed - it will keep you awake.",
        target_phenotypes: ["morning_fatigue"],
        target_gateways: ["excessive_sleepiness"],
        contraindications: ["hyperarousal_insomnia"],
        default_frequency: "daily",
        default_timing: "morning",
        is_optional_addon: true,
        primary_benefit: "Boosts morning alertness",
      },

      // ========== Environment (Evidence A-B) ==========
      {
        intervention_id: "BLACKOUT-01",
        name: "Blackout Curtains / Eye Mask",
        short_name: "Blackout",
        category: "environment",
        type: "environmental",
        evidence_score: 4, // A-B
        why_it_works: "Prevents early-morning light phase advances and awakenings. Light exposure during sleep disrupts melatonin and sleep architecture.",
        how_to_apply: "True blackout curtains; avoid LEDs in room; consider eye mask for travel. Cover all light sources including standby lights.",
        instructions_text: "Use blackout curtains or a comfortable eye mask. Cover any LEDs or standby lights in your bedroom. Complete darkness improves sleep quality.",
        target_phenotypes: ["EMA", "urban_light_pollution", "shift_workers_day_sleeping"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Prevents light-induced awakenings",
        bundle_ids: ["fragile_sleeper"],
      },
      {
        intervention_id: "EARPLUGS-01",
        name: "Earplugs / Noise Control",
        short_name: "Earplugs",
        category: "environment",
        type: "environmental",
        evidence_score: 3, // B
        why_it_works: "Reduces micro-arousals from unpredictable sound. Even sounds that don't wake you fully can fragment sleep architecture.",
        how_to_apply: "Silicone or foam fit; pair with white noise if helpful. Find comfortable fit that stays in place.",
        instructions_text: "Use comfortable earplugs (silicone or foam) to block noise. You can combine these with white noise for best results.",
        target_phenotypes: ["WASO", "noisy_environment", "noisy_partner"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Blocks sleep-fragmenting noise",
        bundle_ids: ["fragile_sleeper"],
      },
      {
        intervention_id: "WHITENOISE-01",
        name: "White Noise",
        short_name: "White Noise",
        category: "environment",
        type: "environmental",
        evidence_score: 3, // B
        why_it_works: "Masks variability; stabilizes auditory environment. Consistent sound covers over intermittent noises that cause arousals.",
        how_to_apply: "Safe volume (conversation level or below); stable sound all night; avoid excessive loudness (hearing considerations).",
        instructions_text: "Use a white noise machine or app at a comfortable volume (no louder than a conversation). Keep it running all night to mask disruptions.",
        target_phenotypes: ["noise_reactive_sleeper"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_optional_addon: true,
        primary_benefit: "Masks disruptive sounds",
        bundle_ids: ["fragile_sleeper"],
      },
      {
        intervention_id: "WEIGHTED-01",
        name: "Weighted Blanket",
        short_name: "Weighted Blanket",
        category: "environment",
        type: "environmental",
        evidence_score: 3, // B
        why_it_works: "'Deep pressure' may reduce arousal/anxiety. RCT shows improved insomnia in psychiatric cohorts (Ekholm et al. 2020).",
        how_to_apply: "~10% body weight; avoid in severe respiratory compromise or claustrophobia. Trial for 2 weeks to assess benefit.",
        instructions_text: "Try a weighted blanket about 10% of your body weight. The deep pressure can help reduce anxiety and improve sleep. Not for those with breathing issues.",
        contraindications: ["severe_respiratory_compromise", "claustrophobia"],
        target_phenotypes: ["anxiety", "ADHD", "psychiatric_insomnia"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        is_optional_addon: true,
        primary_benefit: "Deep pressure calming",
      },

      // ========== Supplements (Evidence B-C) ==========
      {
        intervention_id: "SUP-GLYCINE-01",
        name: "Glycine 3g Pre-Bed",
        short_name: "Glycine",
        category: "supplements",
        type: "supplement",
        evidence_score: 3, // B
        why_it_works: "May support thermoregulation and subjective sleep quality; improves next-day fatigue/alertness in sleep restriction (Bannai et al. 2012).",
        how_to_apply: "3g 30-60 min before bed; monitor GI tolerance. Available as powder or capsules.",
        instructions_text: "Take 3 grams of glycine 30-60 minutes before bed. You can mix powder in water or take capsules. May improve how refreshed you feel.",
        target_phenotypes: ["nonrestorative_sleep", "fatigue_after_short_sleep", "mild_insomnia"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        default_dosage: "3g",
        is_optional_addon: true,
        primary_benefit: "Improves sleep quality and next-day alertness",
      },
      {
        intervention_id: "SUP-MAG-01",
        name: "Magnesium (Glycinate/Citrate)",
        short_name: "Magnesium",
        category: "supplements",
        type: "supplement",
        evidence_score: 3, // B (stronger in deficient/older adults)
        why_it_works: "Neuromuscular relaxation, GABAergic modulation. Some RCT support in older adults with insomnia (Mah & Pitre 2021 meta-analysis).",
        how_to_apply: "Glycinate/citrate forms often better tolerated; avoid in significant renal impairment. 200-400mg elemental magnesium in evening.",
        instructions_text: "Take 200-400mg magnesium (glycinate or citrate form) in the evening. Start with lower dose. Not recommended with kidney problems.",
        contraindications: ["significant_renal_impairment"],
        target_phenotypes: ["older_adults", "dietary_deficiency", "leg_cramps"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        default_timing: "evening",
        default_dosage: "300mg",
        dosage_notes: "Glycinate form best for sleep; citrate if constipation is an issue",
        is_optional_addon: true,
        primary_benefit: "Supports relaxation and muscle comfort",
      },
      {
        intervention_id: "SUP-THEANINE-01",
        name: "L-Theanine",
        short_name: "L-Theanine",
        category: "supplements",
        type: "supplement",
        evidence_score: 3, // B
        why_it_works: "Anxiolytic/relaxation effects; systematic review suggests benefit for sleep outcomes (Cotter et al. 2025).",
        how_to_apply: "200mg in evening; titrate up to 400mg if needed; consider daytime dose for anxiety-prone patients.",
        instructions_text: "Take 200mg L-theanine in the evening for relaxation. Can increase to 400mg if needed. Safe to use during the day for anxiety too.",
        target_phenotypes: ["stress_insomnia", "bedtime_rumination"],
        target_gateways: ["insomnia", "anxiety"],
        default_frequency: "daily",
        default_timing: "evening",
        default_dosage: "200mg",
        is_optional_addon: true,
        primary_benefit: "Reduces stress and promotes relaxation",
      },
      {
        intervention_id: "SUP-GABA-01",
        name: "GABA",
        short_name: "GABA",
        category: "supplements",
        type: "supplement",
        evidence_score: 1, // C
        why_it_works: "Oral bioavailability/CNS penetration debated; some combo trials exist, but standalone evidence is limited/heterogeneous.",
        how_to_apply: "Short trial only; avoid combining with sedatives. Consider only if anxiety prominent and patient prefers nutraceutical trial.",
        instructions_text: "GABA supplements have limited evidence. Try a short 2-week trial if other options haven't helped. Don't combine with sleep medications.",
        contraindications: ["concurrent_sedatives"],
        target_phenotypes: ["anxiety_prominent"],
        target_gateways: ["anxiety"],
        default_frequency: "daily",
        default_timing: "pre_bed",
        is_optional_addon: true,
        primary_benefit: "May reduce anxiety (limited evidence)",
      },
      {
        intervention_id: "SUP-CREATINE-01",
        name: "Creatine",
        short_name: "Creatine",
        category: "supplements",
        type: "supplement",
        evidence_score: 1, // C for sleep; A for performance
        why_it_works: "May reduce perceived fatigue and support cognition under sleep loss via phosphocreatine buffering. Sleep-specific evidence limited.",
        how_to_apply: "3-5g/day; timing flexible; watch for GI issues. Not a sleep aid - helps with cognitive resilience during sleep restriction.",
        instructions_text: "Take 3-5g creatine daily (any time). This doesn't directly improve sleep but may help your brain function better when sleep-deprived.",
        target_phenotypes: ["athletes", "high_cognitive_load", "sleep_restriction"],
        target_gateways: ["excessive_sleepiness"],
        default_frequency: "daily",
        default_timing: "morning",
        default_dosage: "5g",
        is_optional_addon: true,
        primary_benefit: "Supports cognition during sleep debt",
      },

      // ========== Exercise (Evidence A-B) ==========
      {
        intervention_id: "EX-AEROBIC-01",
        name: "Regular Aerobic Activity",
        short_name: "Aerobic Exercise",
        category: "exercise",
        type: "behavioral",
        evidence_score: 5, // A
        why_it_works: "Improves sleep quality, reduces anxiety, supports metabolic health. Regular exercise is a strong foundation for good sleep.",
        how_to_apply: "Start low, build to ≥150 min/wk moderate intensity; track for overtraining. Consistency matters more than intensity.",
        instructions_text: "Aim for at least 150 minutes of moderate exercise per week (like brisk walking). Start where you are and gradually build up. Consistency is key.",
        target_phenotypes: ["fatigue", "metabolic_phenotypes", "anxiety"],
        target_gateways: ["insomnia", "metabolic_risk", "depression"],
        default_frequency: "weekly",
        recommended_duration_weeks: 0, // ongoing
        is_core_intervention: true,
        primary_benefit: "Foundation for sleep health",
        bundle_ids: ["cardiometabolic_alignment"],
      },
      {
        intervention_id: "EX-AM-01",
        name: "Morning Exercise for Phase Advance",
        short_name: "Morning Exercise",
        category: "exercise",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Exercise is a secondary zeitgeber that can advance circadian timing. Morning light + morning exercise creates a strong phase advance signal.",
        how_to_apply: "Light-moderate morning sessions; avoid punishing intensity if sleep-deprived. Combine with morning light exposure.",
        instructions_text: "Exercise in the morning to help shift your body clock earlier. Light to moderate intensity is fine - don't exhaust yourself if you're tired.",
        target_phenotypes: ["delayed_phase", "night_owl_wanting_earlier_schedule"],
        target_gateways: ["circadian_misalignment"],
        default_frequency: "daily",
        default_timing: "morning",
        is_core_intervention: true,
        primary_benefit: "Advances circadian phase",
        bundle_ids: ["delayed_phase_insomnia"],
      },
      {
        intervention_id: "EX-LATE-AVOID-01",
        name: "Avoid Late High-Intensity",
        short_name: "No Late HIIT",
        category: "exercise",
        type: "behavioral",
        evidence_score: 3, // B
        why_it_works: "Catecholamines + core temp elevation can delay sleep for some. Late intense exercise is stimulating and raises body temperature.",
        how_to_apply: "Schedule HIIT earlier in day; late evening: mobility, easy zone 1-2 only. Finish intense exercise ≥3-4h before bed.",
        instructions_text: "Avoid intense exercise within 3-4 hours of bedtime. Late evening is fine for gentle stretching or easy walking, not HIIT or heavy lifting.",
        target_phenotypes: ["SOL", "hyperarousal"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_optional_addon: true,
        primary_benefit: "Prevents exercise-induced sleep delay",
      },

      // ========== Perimenopause (Evidence A-B) ==========
      {
        intervention_id: "MENO-COOL-01",
        name: "Hot Flash Cooling Strategy",
        short_name: "Hot Flash Cooling",
        category: "perimenopause",
        type: "environmental",
        evidence_score: 3, // B
        why_it_works: "Vasomotor symptoms fragment sleep; cooling reduces awakenings. Hot flashes disrupt sleep; environmental cooling helps.",
        how_to_apply: "Layered bedding, cool room, breathable fabrics; consider medical evaluation for HRT appropriateness if symptoms severe.",
        instructions_text: "Use layered bedding you can easily remove, keep the room cool, and choose breathable fabrics. Talk to your doctor about other options if symptoms are severe.",
        target_phenotypes: ["perimenopause", "night_sweats"],
        target_gateways: ["insomnia"],
        default_frequency: "daily",
        is_core_intervention: true,
        primary_benefit: "Manages vasomotor symptoms",
      },
      {
        intervention_id: "MENO-STRENGTH-01",
        name: "Strength Training (Menopause)",
        short_name: "Strength Training",
        category: "perimenopause",
        type: "behavioral",
        evidence_score: 4, // A-B
        why_it_works: "Improves insulin sensitivity and body composition; supports sleep indirectly via metabolic stability. Counteracts menopausal metabolic changes.",
        how_to_apply: "2-3 sessions/week; progressive overload. Focus on major muscle groups. Can combine with HRT if appropriate.",
        instructions_text: "Do strength training 2-3 times per week. This helps maintain muscle mass and metabolic health during menopause, which indirectly improves sleep.",
        target_phenotypes: ["midlife_women", "sarcopenia_risk"],
        target_gateways: ["metabolic_risk"],
        default_frequency: "weekly",
        is_core_intervention: true,
        primary_benefit: "Supports metabolic health through menopause",
      },

      // ========== Medical Screens (Evidence A) ==========
      {
        intervention_id: "MED-OSA-01",
        name: "Screen for OSA/SDB",
        short_name: "OSA Screening",
        category: "medical",
        type: "medical",
        evidence_score: 5, // A
        why_it_works: "Untreated OSA breaks sleep architecture and drives fatigue and cardiometabolic risk. Must screen before other interventions will work.",
        how_to_apply: "STOP-BANG screening; HSAT/PSG if indicated; treat with CPAP/oral appliance/surgery as appropriate. Screen anyone with snoring, witnessed apneas, HTN, high BMI, or unexplained sleepiness.",
        instructions_text: "If you snore, have high blood pressure, or feel excessively sleepy despite enough sleep time, get screened for sleep apnea. This is critical - other interventions won't work if OSA is untreated.",
        target_phenotypes: ["snoring", "witnessed_apneas", "hypertension", "high_BMI", "sleepiness"],
        target_gateways: ["sleep_apnea"],
        default_frequency: "once",
        is_core_intervention: true,
        primary_benefit: "Identifies treatable breathing disorder",
        bundle_ids: ["delayed_phase_insomnia", "cardiometabolic_alignment"],
      },
      {
        intervention_id: "MED-RLS-01",
        name: "Restless Legs / Iron Screen",
        short_name: "RLS/Iron Check",
        category: "medical",
        type: "medical",
        evidence_score: 4, // A-B
        why_it_works: "Periodic limb movements fragment sleep. Iron deficiency worsens RLS symptoms and is treatable.",
        how_to_apply: "Ferritin check (target >75 for RLS); treat iron deficiency; review medications that worsen RLS (antihistamines, SSRIs, etc.).",
        instructions_text: "If you have an urge to move your legs at night or restlessness that's relieved by movement, get checked for restless legs syndrome and iron deficiency.",
        target_phenotypes: ["urge_to_move_legs", "relief_with_movement"],
        target_gateways: ["insomnia"],
        default_frequency: "once",
        is_core_intervention: true,
        primary_benefit: "Identifies treatable leg restlessness",
      },
    ];

    for (const intv of interventions) {
      const existing = await ctx.db.query("interventions").withIndex("by_intervention_id", q => q.eq("intervention_id", intv.intervention_id)).first();
      if (!existing) {
        await ctx.db.insert("interventions", {
          intervention_id: intv.intervention_id,
          name: intv.name,
          short_name: intv.short_name,
          category: intv.category,
          type: intv.type,
          why_it_works: intv.why_it_works,
          how_to_apply: intv.how_to_apply,
          instructions_text: intv.instructions_text,
          target_phenotypes_json: intv.target_phenotypes ? JSON.stringify(intv.target_phenotypes) : undefined,
          target_gateways_json: intv.target_gateways ? JSON.stringify(intv.target_gateways) : undefined,
          contraindications_json: intv.contraindications ? JSON.stringify(intv.contraindications) : undefined,
          evidence_score: intv.evidence_score,
          default_frequency: intv.default_frequency,
          default_timing: intv.default_timing,
          default_dosage: intv.default_dosage,
          dosage_notes: intv.dosage_notes,
          recommended_duration_weeks: intv.recommended_duration_weeks,
          is_core_intervention: intv.is_core_intervention,
          is_optional_addon: intv.is_optional_addon,
          primary_benefit: intv.primary_benefit,
          bundle_ids_json: intv.bundle_ids ? JSON.stringify(intv.bundle_ids) : undefined,
          status: "active",
          version: 1,
          created_at: now,
          updated_at: now,
        });
        interventionsCreated++;
      }
    }

    // ============================================
    // BUNDLES (Ready-to-prescribe protocols from v2)
    // ============================================
    const bundles = [
      {
        bundle_id: "delayed_phase_insomnia",
        name: "Delayed Phase + Insomnia (2-week)",
        description: "For delayed-phase chronotype with insomnia. Combines circadian phase advance with CBT-I core interventions.",
        goal: "Advance circadian phase and improve sleep onset/maintenance",
        target_phenotypes: ["delayed_phase", "SOL", "WASO"],
        target_gateways: ["insomnia", "circadian_misalignment"],
        core_intervention_ids: ["WAKE-ANCHOR-01", "LIGHT-AM-01", "LIGHT-PM-01", "MEAL-LAST-01", "CBTI-SC-01", "CAFF-CUTOFF-01"],
        optional_intervention_ids: ["CBTI-SR-01", "LIGHT-BOX-01", "SJL-01"],
        recommended_count: 6,
        tracking_metrics: ["sleep_latency", "wake_time_variability", "sleep_efficiency"],
      },
      {
        bundle_id: "cardiometabolic_alignment",
        name: "Cardiometabolic Alignment (4-week)",
        description: "For patients with cardiometabolic risk (prediabetes, HTN, obesity). Aligns circadian rhythms for metabolic health.",
        goal: "Align circadian rhythms to improve metabolic markers",
        target_phenotypes: ["cardiometabolic_risk", "prediabetes", "hypertension", "obesity"],
        target_gateways: ["metabolic_risk"],
        core_intervention_ids: ["ETRE-01", "LIGHT-AM-01", "WAKE-ANCHOR-01", "EX-AEROBIC-01", "CAFF-CUTOFF-01", "MED-OSA-01"],
        optional_intervention_ids: ["EX-AM-01", "MEAL-LAST-01"],
        recommended_count: 6,
        tracking_metrics: ["eating_window", "wake_time_regularity", "exercise_minutes"],
      },
      {
        bundle_id: "fragile_sleeper",
        name: "Noise/Light Fragile Sleeper",
        description: "For patients highly sensitive to environmental disruptions. Optimizes sleep environment for continuity.",
        goal: "Create optimal sleep environment to reduce fragmentation",
        target_phenotypes: ["noise_sensitive", "light_sensitive", "WASO"],
        target_gateways: ["insomnia"],
        core_intervention_ids: ["BLACKOUT-01", "EARPLUGS-01", "BATH-01", "COOL-ROOM-01"],
        optional_intervention_ids: ["WHITENOISE-01", "WEIGHTED-01", "DARK-01"],
        recommended_count: 4,
        tracking_metrics: ["waso", "awakenings", "sleep_quality_rating"],
      },
      {
        bundle_id: "maintenance_insomnia",
        name: "Sleep Maintenance Insomnia",
        description: "For patients who fall asleep fine but wake frequently during the night.",
        goal: "Consolidate sleep and reduce middle-of-night awakenings",
        target_phenotypes: ["WASO", "fragmented_sleep"],
        target_gateways: ["insomnia"],
        core_intervention_ids: ["CBTI-SR-01", "CBTI-SC-01", "COOL-ROOM-01", "ALCOHOL-01", "BLACKOUT-01"],
        optional_intervention_ids: ["EARPLUGS-01", "MED-OSA-01"],
        recommended_count: 5,
        tracking_metrics: ["waso", "sleep_efficiency", "awakenings"],
      },
    ];

    for (const bundle of bundles) {
      const existing = await ctx.db.query("intervention_bundles").withIndex("by_bundle_id", q => q.eq("bundle_id", bundle.bundle_id)).first();
      if (!existing) {
        await ctx.db.insert("intervention_bundles", {
          bundle_id: bundle.bundle_id,
          name: bundle.name,
          description: bundle.description,
          goal: bundle.goal,
          target_phenotypes_json: JSON.stringify(bundle.target_phenotypes),
          target_gateways_json: bundle.target_gateways ? JSON.stringify(bundle.target_gateways) : undefined,
          core_intervention_ids_json: JSON.stringify(bundle.core_intervention_ids),
          optional_intervention_ids_json: bundle.optional_intervention_ids ? JSON.stringify(bundle.optional_intervention_ids) : undefined,
          recommended_count: bundle.recommended_count,
          tracking_metrics_json: bundle.tracking_metrics ? JSON.stringify(bundle.tracking_metrics) : undefined,
          status: "active",
          created_at: now,
          updated_at: now,
        });
        bundlesCreated++;
      }
    }

    return {
      categories: categoriesCreated,
      interventions: interventionsCreated,
      bundles: bundlesCreated,
    };
  },
});
